### PR TITLE
Split fluids by temperature

### PR DESCRIPTION
**Pull request by Sopel97**
This PR introduces splitting fluids by temperature into more fluids and assigns recipes such that fluid temperatures are respected.
Notably it allows solving the hot air chain in pymods that heavily relies on fluid temperature (and similar chains).

An option was added to the main screen above expensive recipe checkbox to toggle this splitting. This option could be defaulted to true and removed in the future. Projects that use non-split fluids are incompatibile with the option set.

### CODE REVIEW

**Comment by ShadowTheAge** [comment]
Hi, thanks for your contribution!
I don't have time right now to check the pull request and play with it, but hopefully I'll have some time later this week or at least the next weekend

However, here are some things to consider:
- fluid temperature should not be part of fluid id. Because YAFC projects should not break on recipe change or introduction of another mod (that may add another fluid temperature breakpoint).
- fluid temperatures could overlap. For example one recipe may produce 100d fluid, another may produce 200d fluid, and one recipe may have "any fluid" requirement while another "only 100d"

These two issues make splitting fluid by temperature very difficult. Any solution can work in one mod(s) but break computations in another mod(s). I don't think "fluid with temperature" should be two separate `FactorioObject`'s but should be solved at the `RecipeLink` stage (`RecipeLink` may have min/max temperature set up automatically and/or manually)

**Comment by Sopel97** [comment]
> fluid temperature should not be part of fluid id. Because YAFC projects should not break on recipe change or introduction of another mod (that may add another fluid temperature breakpoint).
That's a valid concern.

> I don't think "fluid with temperature" should be two separate FactorioObject's but should be solved at the RecipeLink stage (RecipeLink may have min/max temperature set up automatically and/or manually)
I was thinking about doing it at the solver level, but the presented solution was easier for me to implement and it was sound to me at the time of writing it. This could be the ultimate solution.

> fluid temperatures could overlap. For example one recipe **[A]** may produce 100d fluid, another **[B]** may produce 200d fluid, and one recipe **[C]** may have "any fluid" requirement while another **[D]** "only 100d"
The solution to this is to include all variants of recipe **[C]** and let the solver do its thing.

Some people expressed interest in this on the pymods discord, so I think it would be valuable to have even as an option with warnings related to the first point.

**Comment by ShadowTheAge** [comment]
I have experimented with fluid separating but unfortunately I wasn't able to reach a solution that I like. Yes, id splitting is the easiest (because you don't need to modify GUI) but it also breaks a lot of things.

I have tested your solution a bit:

I like:
- it works
- fluids of different temperatures may have different costs, and different milestones

I don't like (implementation problems):
- Splitting is very slow. O(n^2) algoritms are everywhere. I have test modpack with more than 100000 objects and it just freezes there for more than a minute. And even on py splitting takes 5 times more time than parsing everything else.
- It doesn't take into account the fact that recipes may have multiple instances of the same fluid as ingridients. In this case it will reference invalid fluids.
- ID concatenation for recipes is easy to break as the concatenated temperature doesn's specify what fluid it is attached to. Also "." (dot) is better for concatenation because Factorio names can't contain dot.

I don't like (approach problems):
- ID change is definetly a "no" for a default option (but may be ok for some sort of advanced option).
- With split fluids some functionality is lost, when you produce two different temperatures but that does not matter and you can mix it (this is ok to drop I think)
- Selecting recipes (eg to produce something) become annoying as you have a lot of copies of the same recipe (Look at ways to make tin ore for example). Same goes for NEIE - copies introduce noise. That may become very annoying if the amount of options becomes high.
- ... which may happen because of "combinatorial explosion" - if a recipe have 3 fluids and each of them have 5 breakpoints - you have 125 copies of a recipe

Now I need time to think about it, and, unfortunately, this week is going to be busy :(

**Comment by Sopel97** [comment]
With pymods removal of the old fluids/recipes from allObjects was taking the longest so I at least improved the performance of that. With pymods the fluid splitting phase should now be a few times faster (it takes about 5-10% of the all loading time for me now). I haven't considered modpacks larger than py; algorithmic changes are inevitable if we want to handle them well.

> It doesn't take into account the fact that recipes may have multiple instances of the same fluid as ingridients. In this case it will reference invalid fluids.

that's a degenerate case if I ever saw one. still, should be possible to adapt the current algorithm by performing the ingredient replacement multiple times for the same fluid for such recipes.

> ID concatenation for recipes is easy to break as the concatenated temperature doesn's specify what fluid it is attached to. Also "." (dot) is better for concatenation because Factorio names can't contain dot.

Name mangling can be improved without breaking things I think.

> I think I would be "ok" with splitting fluids as an option if not for splitting recipes.
Steam 60 and Steam 165 feel like a different fluid, but "mining using steam 60" and "mining using steam 165" doesn't feel like different recipes.

So I was thinking about this, but the problem I see is that you cannot have one recipe that takes either one of the ingredients. This would require deeper changes.

I agree with the rest. I think we should leave the discussion at that. I'll keep the PR open for people to be able to discover the branch that allows this. We'll revisit making this better in the future.

**Comment by ShadowTheAge** [comment]
I was thinking quite a lot about the fluid temperature problem. I was postponing it because I couldn't find solution that was good enough for me

But I guess if people start merge-requesting it, I have to do something :)

So, this is now high priority.

**Comment by ShadowTheAge** [comment]
Hi
I have implemented a prototype of the split fluid system if you would like to check
It can be tested in this bracnh: https://github.com/ShadowTheAge/yafc/tree/split-fluids-b

- I have split fluids but no split recipes. Instead recipe ingredient now can have "variants" of goods that they can link to.
- This is an "id split" but the system starts to match the fluid with closest temperature instead of requiring exact match.
- Because this is an "id split" system it will be hidden under some sort of advanced options.

Also, can I ask you have your .yafc file you were using for testing?

**Comment by TwentyEighty** [comment]
Here's something from that I was able to get working right on Sopel's build but not this one, from pySuite
image

The idea here is that you can heat up the 250 degree outlet-gas-4 and turn it into 1000 degree outlet-gas-4

Same in this one, where you take 165 or even 60 degree steam and heat it to 500

image

**Comment by Sopel97** [comment]
> Also, can I ask you have your .yafc file you were using for testing?

I don't, I wasn't saving stuff because I was making many breaking changes during developement and it was breaking often anyway.

**Comment by ShadowTheAge** [comment]
@TwentyEighty well it is possible, just not straightforward to setup.
Manual selection of fluid variant is possible but not yet implemented

**Comment by ShadowTheAge** [comment]
@TwentyEighty I have added selection of fluid variants
The only thing I know that doesn't fully work right now is cost analysis may get confused

**Comment by TwentyEighty** [comment]
It sure seems to work pretty nicely! It even picks the "correct" fluid variant automatically for these two examples. I don't know how you did that but 👍 

The steam valuation seems correctish to me, it even thinks that 500 is cheaper than 165 since you can use "junk" 60 steam to make it, which I guess makes sense. The outlet-gas-4 valuation is the one that seems wrong.

**Comment by Sopel97** [comment]
It thinks 500d steam is cheap because it thinks getting heat is cheap, which is not true in py. Could be the next target for improvement.

**Pull request closed without merging**
